"""Direction reuse preserves the original terminal and confidence semantics."""
import pytest
import map_analysis


def test_map_asset_identity_ignores_regenerated_statistics_probe(tmp_path, monkeypatch):
    import map_geometry
    managed = tmp_path/'managed'; managed.mkdir()
    runtime = tmp_path/'runtime'; runtime.mkdir()
    (managed/'Assembly-CSharp.dll').write_bytes(b'original assembly')
    (runtime/'UnityEngine.dll').write_bytes(b'unity')
    probe = runtime/'Assembly-CSharp.probe.dll'
    probe.write_bytes(b'old generated statistics probe')
    generator = tmp_path/'patch.py'; generator.write_text('# map probe generator')
    monkeypatch.setattr(map_geometry, 'probe_script', lambda: generator)
    service = map_geometry.MapGeometryService(tmp_path/'cache', managed, runtime)
    before = service._asset_signature()
    probe.write_bytes(b'regenerated by concurrent statistics parser')
    assert service._asset_signature() == before
    probe.unlink()
    assert service._asset_signature() == before
    generator.write_text('# changed actual map probe generator')
    assert service._asset_signature() != before
from pathlib import Path


def test_fresh_load_bypasses_existing_disk_cache_and_keeps_only_memory(tmp_path,monkeypatch):
    import json
    import subprocess
    import sys
    import map_geometry

    save=tmp_path/'city.save'; save.write_bytes(b'read only sample')
    managed=tmp_path/'managed'; managed.mkdir()
    (managed/'Assembly-CSharp.dll').write_bytes(b'assembly')
    runtime=tmp_path/'runtime'; runtime.mkdir()
    (runtime/'UnityEngine.dll').write_bytes(b'unity')
    (runtime/'Assembly-CSharp.probe.dll').write_bytes(b'probe')
    (runtime/'map_assets.json').write_text('{}',encoding='utf-8')
    cache=tmp_path/'cache'
    worker=tmp_path/'worker.py'
    worker.write_text(
        'import json,sys\nfrom pathlib import Path\n'
        'sys.path.insert(0,sys.argv[2])\nimport map_geometry\n'
        'c=json.loads(Path(sys.argv[1]).read_text())\n'
        'data=dict(roads={},buildings=[],stops={},lines=[],diagnostics=[],junctions=[])\n'
        'if c.get("geometry_format")=="ndjson":\n'
        '    map_geometry._write_geometry_ndjson(data,Path(c["job"])/"geometry.ndjson")\n'
        'else:\n    (Path(c["job"])/"geometry.json").write_text(json.dumps(data))\n',encoding='utf-8')
    launches=[]
    original=subprocess.Popen
    def launch(command,**kwargs):
        config=json.loads(Path(command[-1]).read_text(encoding='utf-8'))
        launches.append(config)
        return original([sys.executable,str(worker),command[-1],str(Path(map_geometry.__file__).parent)],**kwargs)
    monkeypatch.setattr(map_geometry.subprocess,'Popen',launch)
    make=lambda:map_geometry.MapGeometryService(cache_dir=cache,managed_root=managed,runtime_data=runtime)
    disk=make().load(save)
    entries={p.name:p.read_bytes() for p in cache.iterdir() if p.is_file()}
    service=make()
    fresh=service.load(save,use_disk_cache=False)
    assert fresh==disk and len(launches)==2
    assert service.load(save,use_disk_cache=False) is fresh
    assert len(launches)==2
    assert {p.name:p.read_bytes() for p in cache.iterdir() if p.is_file()}==entries
    assert launches[-1]['geometry_format']=='ndjson'
    assert launches[-1]['catalog_cache'].startswith(launches[-1]['job'])
    assert not Path(launches[-1]['job']).exists()


def test_geometry_ndjson_preserves_records_and_rejects_truncation_or_cancel(tmp_path):
    import map_geometry
    data=dict(roads={'2':dict(id=2,curves=[[[0.,0.,0.],[1.5,0.,0.],[2.,0.,0.],[3.,0.,0.]]]),
                     '1':dict(id=1,value=None)},
              buildings=[dict(id=4,name='秋山',known_zero=0,missing=None)],
              stops={'5':dict(id=5,name='转车站')},lines=[dict(id=6,legs=[{'roads':[]}])],
              diagnostics=['未知','zero:0'],junctions=[dict(id=7,connections=[])])
    target=tmp_path/'geometry.ndjson'
    map_geometry._write_geometry_ndjson(data,target)
    restored=map_geometry._read_geometry_ndjson(target)
    assert restored==data
    assert tuple(restored['roads'])==('2','1')
    calls=0
    def cancel():
        nonlocal calls
        calls+=1
        return calls==4
    with pytest.raises(map_geometry.MapCancelled):
        map_geometry._read_geometry_ndjson(target,cancel)
    lines=target.read_text(encoding='utf-8').splitlines()
    target.write_text('\n'.join(lines[:-1])+'\n',encoding='utf-8')
    with pytest.raises(ValueError,match='Incomplete'):
        map_geometry._read_geometry_ndjson(target)


@pytest.mark.parametrize('height', [0., 12.])
def test_cached_direction_scores_match_per_terminal_computation(monkeypatch, height):
    points=((0.,0.,0.),(100.,0.,0.),(200.,0.,0.),(300.,0.,0.),
            (200.,height,2.),(100.,height,2.),(0.,height,2.))
    legs=tuple(((a,((a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2),b),)
               for a,b in zip(points,points[1:]))
    names=('', '', '', '东北转车站E2', '', '', '')
    cached=map_analysis.infer_direction(points,legs,names)
    monkeypatch.setattr(map_analysis,'_cached_geometry_similarity',lambda *args: None)
    original=map_analysis.infer_direction(points,legs,names)
    assert cached==original


def test_cached_direction_checks_cancellation_during_similarity():
    points=tuple((float(i*100),0.,0.) for i in range(4))
    legs=tuple(((a,b),) for a,b in zip(points,points[1:]))
    class Cancelled(Exception):
        pass
    calls=0
    def cancel():
        nonlocal calls
        calls+=1
        if calls==1:
            raise Cancelled()
    with pytest.raises(Cancelled):
        map_analysis.infer_direction(points,legs,cancelled=cancel)


def _direction_jobs():
    points=((0.,0.,0.),(100.,0.,0.),(200.,0.,0.),(100.,0.,1.),(0.,0.,1.))
    legs=tuple(((a,b),) for a,b in zip(points,points[1:]))
    return [(i,points,legs,['','','','','']) for i in range(8)]


def test_parallel_direction_worker_matches_serial(tmp_path):
    import map_geometry
    jobs=_direction_jobs()
    result=map_geometry._parallel_directions(jobs,tmp_path)
    expected=map_analysis.infer_direction(jobs[0][1],jobs[0][2],jobs[0][3])
    assert result=={i:expected for i in range(8)}


def test_parallel_direction_cancel_terminates_all_workers(tmp_path,monkeypatch):
    import subprocess
    import sys
    import map_geometry
    marker=tmp_path/'started'
    sleeper=tmp_path/'sleeper.py'
    sleeper.write_text('import sys,time\nfrom pathlib import Path\nPath(sys.argv[1]).write_text("started")\ntime.sleep(20)\n',encoding='utf-8')
    original=subprocess.Popen
    launched=[]
    def launch(command,**kwargs):
        process=original([sys.executable,str(sleeper),str(marker)],**kwargs)
        launched.append(process)
        return process
    monkeypatch.setattr(map_geometry.subprocess,'Popen',launch)
    with pytest.raises(map_geometry.MapCancelled):
        map_geometry._parallel_directions(_direction_jobs(),tmp_path,marker.exists)
    assert launched and all(process.poll() is not None for process in launched)


def test_parallel_direction_failure_is_explicit_and_cleans_workers(tmp_path,monkeypatch):
    import subprocess
    import sys
    import map_geometry
    failure=tmp_path/'failure.py'; failure.write_text('raise SystemExit(3)\n',encoding='utf-8')
    original=subprocess.Popen
    launched=[]
    def launch(command,**kwargs):
        process=original([sys.executable,str(failure)],**kwargs)
        launched.append(process)
        return process
    monkeypatch.setattr(map_geometry.subprocess,'Popen',launch)
    with pytest.raises(RuntimeError,match='Map direction analysis failed'):
        map_geometry._parallel_directions(_direction_jobs(),tmp_path)
    assert launched and all(process.poll() is not None for process in launched)
